# FILEPATH: docker-compose.yml
version: '3'

services:
    watchtower:
        image: containrrr/watchtower
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    registry:
        image: registry:2
        restart: always
        ports:
            - "5000:5000"
        volumes:
            - registry_data:/var/lib/registry

    yacht:
        image: selfhostedpro/yacht
        container_name: yacht
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "yacht:/config"

volumes:
    portainer_data:
    registry_data:
    yacht:
